#include "parser/parser.h"
#include "ast_executor.h"
#include "ast_executor.h"
#include "repl.h"
#include "bytecode.h"

#define USE_BYTECODE 1

// creates string variable str, executes body and frees the string afterwards
#define USING_STRING(string_expression, body) { char* str=string_expression; body; free(str); }

void execute_file(const char* file_name){
    parse_file(file_name);
    table* global_scope=new_table();
    global_scope->ref_count++;
    register_globals(global_scope);
    //USING_STRING(stringify_expression(parsing_result, 0),
    //    printf(str));
    printf("\nExecuting parsing result:\n");
    object* execution_result;
    if(USE_BYTECODE){
        bytecode_program prog=ast_to_bytecode(parsing_result, 1);
        delete_expression(parsing_result);// at this point ast is useless and only wastes memory

        //USING_STRING(stringify_bytecode(prog), 
        //   printf("Generated bytecode:\n%s\n", str));

        execution_result=execute_bytecode(prog.code, prog.constants, global_scope);
        free(prog.code);
        free((char*)prog.constants);
    } else {
        execution_result=execute_ast(parsing_result, global_scope, 1);
        delete_expression(parsing_result);
    }
    USING_STRING(stringify(execution_result), 
        printf("Execution result:\n%s\n", str));
    USING_STRING(stringify(global_scope), 
        printf("Global scope:\n%s\n", str));
    
    object_delete(global_scope);
    object_delete(execution_result);
}

int main(int argc, char *argv[]){
    if(argc>2){
        printf("Too many arguments.");
    } else if(argc<2){
        repl();
    } else {
        TRY_CATCH(
            execute_file(argv[1]);
        ,
            printf("Error occured on line %i of parsed code:\n", current_line);
            printf(err_message);
            exit(-1);
        )
    }
}