#!/bin/sh

# make sure that the newline encoding is right
source_files=$(find . \
			  ! -name "tests.c" \
			  ! -name "main.c" \
			  ! -path "./object_system*" \
			  ! -path "./parser*" \
			  ! -path "./myjit*" \
			  -name "*.c");
		
# remove newlines
source_files=$(echo $source_files | tr '\n' ' ');

# take source files and replace their extensions to .o
# remove local path prefixes, because gcc puts them in the main folder
object_files=$(echo $source_files | sed -e "s/\.c/\.o/g" | xargs basename -a);
object_files=$(echo $object_files | tr '\n' ' ');

echo "source-files:=$source_files\n" "object-files:=$object_files" > Makefile ;
cat Makefile.in >> Makefile ;